OpenAI.NET.sln
OpenAI.NET/OpenAI.NET.csproj

INFRA: Initialize Open AI Core

---

OpenAI.NET.Tests.Unit/DeleteMe.cs
OpenAI.NET.Tests.Unit/OpenAI.NET.Tests.Unit.csproj
OpenAI.NET.sln

INFRA: Initialize Unit Test Project

---

OpenAI.NET.Test.Acceptance/DeleteMe.cs
OpenAI.NET.Test.Acceptance/OpenAI.NET.Test.Acceptance.csproj
OpenAI.NET.sln

INFRA: Initialize Acceptance Project

---

OpenAI.NET.Infrastructure.Build/Program.cs

CODERUB: add-copyright-program.cs

---

OpenAI.NET.Infrastructure.Build/Program.cs

CODE RUB: Add Namespace to Build Project

---

OpenAI.NET/Brokers/OpenAIs/IOpenAIBroker.cs
OpenAI.NET/Brokers/OpenAIs/OpenAIBroker.cs
OpenAI.NET/Models/Configurations/ApiConfigurations.cs
OpenAI.NET/OpenAI.NET.csproj

BROKERS: Initialize API Broker

---

OpenAI.NET.Tests.Acceptance/OpenAI.NET.Tests.Acceptance.csproj
OpenAI.NET.Tests.Unit/OpenAI.NET.Tests.Unit.csproj

CONFIGS: Update All Libraries

---

OpenAI.NET/Services/Foundations/Completions/CompletionService.Validations.cs

CODE RUB:Add Static To Validation Methods

---

.github/dependabot.yml

Added dependabot support for auto package updates.

INFRA: Added dependabot to the project.

---

OpenAI.NET.Tests.Integration/DeleteMe.cs
OpenAI.NET.Tests.Integration/OpenAI.NET.Tests.Integration.csproj
OpenAI.NET.sln

INFRA: Initialize Integration Tests Project

---

OpenAI.NET.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Exceptions.Prompt.cs
OpenAI.NET.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Logics.Prompt.cs
OpenAI.NET.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Validations.Prompt.cs
OpenAI.NET.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.cs
OpenAI.NET/Brokers/OpenAIs/OpenAIBroker.Completions.cs
OpenAI.NET/Brokers/OpenAIs/OpenAIBroker.cs
OpenAI.NET/Models/Completions/Exceptions/InvalidCompletionException.cs
OpenAI.NET/Models/ExternalCompletions/ExternalCompletionRequest.cs
OpenAI.NET/Services/Foundations/Completions/CompletionService.Exceptions.cs
OpenAI.NET/Services/Foundations/Completions/CompletionService.cs

- Fix naming issue
- Run Code Clean up
- Fix namespaces for foundation services tests

CODE RUB: Clean up

---

OpenAI.NET/Clients/Completions/CompletionsClient.cs
OpenAI.NET/Clients/Completions/ICompletionClient.cs
OpenAI.NET/Models/Clients/Completions/Exceptions/CompletionClientDependencyException.cs
OpenAI.NET/Models/Clients/Completions/Exceptions/CompletionClientServiceException.cs
OpenAI.NET/Models/Clients/Completions/Exceptions/CompletionClientValidationException.cs

CLIENTS: Completion Client

---

.gitignore

MINOR FIX: Update RESTFulSense

---

OpenAI.NET.Tests.Unit/OpenAI.NET.Tests.Unit.csproj

Removed the duplicate package reference form csproj file

CODE RUB: Removed Duplicate PackageReference #64

---

README.md

DOCUMENTATION: Add Contribution Rules

---

OpenAI.NET.Tests.Acceptance/Clients/Completions/CompletionClientTests.Prompts.cs

MINOR FIX: Add Content-Type application/json Match Header To Completion Client Acceptance Test

---

.github/workflows/dotnet.yml

MINOR FIX: Inconsistency Between dotnet.yml and Infrastructure Build Project

---

OpenAI.NET.Infrastructure.Build/Program.cs

CODE RUB: Fix Indentation In Infrastructure Build Project

---

OpenAI.NET.Tests.Acceptance/Clients/Completions/CompletionClientTests.Prompts.cs
OpenAI.NET.Tests.Acceptance/Clients/Completions/CompletionClientTests.cs

CODE RUB: Resolve Comments Of Stef on WireMock

---

OpenAI.NET.Tests.Integration/APIs/Completions/CompletionsApiTests.Prompts.cs
OpenAI.NET.Tests.Integration/APIs/Completions/CompletionsApiTests.cs
OpenAI.NET.Tests.Integration/OpenAI.NET.Tests.Integration.csproj

INTEGRATIONS: Completions Prompt

---

.github/workflows/dotnet.yml
OpenAI.NET.Infrastructure.Build/Program.cs
OpenAI.NET.Tests.Integration/APIs/Completions/CompletionsApiTests.Prompts.cs

INFRA: Add Env Variables/Github Secrets

---

OpenAI.NET.Tests.Integration/APIs/Completions/CompletionsApiTests.Prompts.cs

CODE RUB: Add Skip on the Integrations Test

---

Standard.AI.OpenAI.Tests.Acceptance/Clients/Completions/CompletionClientTests.Prompts.cs

CODE RUB: Remove Unnecessary Assignment

---

Standard.AI.OpenAI/Models/Services/Foundations/ExternalChatCompletions/ExternalChatCompletionChoice.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalChatCompletions/ExternalChatCompletionMessage.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalChatCompletions/ExternalChatCompletionRequest.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalChatCompletions/ExternalChatCompletionResponse.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalChatCompletions/ExternalChatCompletionUsage.cs

DATA: External Chat Models

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Logics.Prompt.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalCompletions/ExternalCompletionChoice.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalCompletions/ExternalCompletionResponse.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalCompletions/ExternalCompletionUsage.cs

CODE RUB: External Completion Model Naming and Accessibility

---

README.md

DOCUMENTATIONS: Find Accounts of Hassan Habib And Link Them

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Exceptions.Prompt.cs
Standard.AI.OpenAI/Services/Foundations/Completions/CompletionService.Exceptions.cs

CODE RUB: Ordered exceptions and test

---

Standard.AI.OpenAI.Tests.Acceptance/Clients/Completions/CompletionClientTests.cs
Standard.AI.OpenAI.Tests.Integration/APIs/Completions/CompletionsApiTests.Prompts.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Logics.Prompt.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Validations.Prompt.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/CompletionRequest.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalCompletions/ExternalCompletionRequest.cs
Standard.AI.OpenAI/Services/Foundations/Completions/CompletionService.Validations.cs
Standard.AI.OpenAI/Services/Foundations/Completions/CompletionService.cs

CODE RUB: Change Model Prompt Property Name To Prompts

---

Standard.AI.OpenAI/Brokers/OpenAIs/OpenAIBroker.cs
Standard.AI.OpenAI/Standard.AI.OpenAI.csproj

CONFIG: Update RESTFulSense and Rename Parameter

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Validations.Prompt.cs
Standard.AI.OpenAI/Services/Foundations/Completions/CompletionService.Validations.cs

CODE RUB: Update Rule Message

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Exceptions.Prompt.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Logics.Prompt.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Validations.Prompt.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.cs
Standard.AI.OpenAI/Services/Foundations/Completions/CompletionService.cs

CODE RUB: Fix Variable Naming in CompletionService

---

README.md

DOCUMENTATION: Fix Variable Naming in Code Example

---

Standard.AI.OpenAI/Models/Services/Foundations/ExternalCompletions/ExternalCompletionRequest.cs

MEDIUM FIX: Correct Json Property Alignment External Completion Request

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ChatCompletions/ChatCompletionServiceTests.Exceptions.Send.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ChatCompletions/ChatCompletionServiceTests.Logics.Send.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ChatCompletions/ChatCompletionServiceTests.Validations.Send.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ChatCompletions/ChatCompletionServiceTests.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/ChatCompletion.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/ChatCompletionChoice.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/ChatCompletionMessage.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/ChatCompletionRequest.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/ChatCompletionResponse.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/ChatCompletionUsage.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/ChatCompletionDependencyException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/ChatCompletionDependencyValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/ChatCompletionServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/ChatCompletionValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/ExcessiveCallChatCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/FailedChatCompletionServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/FailedServerChatCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/InvalidChatCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/InvalidConfigurationChatCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/NotFoundChatCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/NullChatCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/UnauthorizedChatCompletionException.cs
Standard.AI.OpenAI/Services/Foundations/ChatCompletions/ChatCompletionService.Exceptions.cs
Standard.AI.OpenAI/Services/Foundations/ChatCompletions/ChatCompletionService.Validations.cs
Standard.AI.OpenAI/Services/Foundations/ChatCompletions/ChatCompletionService.cs
Standard.AI.OpenAI/Services/Foundations/ChatCompletions/IChatCompletionService.cs
Standard.AI.OpenAI/Services/Foundations/Completions/CompletionService.Exceptions.cs

FOUNDATIONS: Send Chat Completion

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ChatCompletions/ChatCompletionServiceTests.Validations.Send.cs
Standard.AI.OpenAI/Models/Clients/Completions/Exceptions/CompletionClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/Completions/Exceptions/CompletionClientServiceException.cs
Standard.AI.OpenAI/Models/Clients/Completions/Exceptions/CompletionClientValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/FailedChatCompletionServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/CompletionDependencyException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/CompletionDependencyValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/CompletionServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/ExcessiveCallCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/FailedCompletionServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/FailedServerCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/InvalidCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/InvalidConfigurationCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/NotFoundCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/UnauthorizedCompletionException.cs
Standard.AI.OpenAI/Services/Foundations/ChatCompletions/ChatCompletionService.Exceptions.cs
Standard.AI.OpenAI/Services/Foundations/ChatCompletions/ChatCompletionService.Validations.cs

CODE RUB: Make Completion / CompletionClient Exceptions Public

---

Standard.AI.OpenAI.Tests.Acceptance/Clients/ChatCompletions/ChatCompletionClientTests.Prompts.cs
Standard.AI.OpenAI.Tests.Acceptance/Clients/ChatCompletions/ChatCompletionClientTests.Send.cs
Standard.AI.OpenAI.Tests.Acceptance/Clients/ChatCompletions/ChatCompletionClientTests.cs

ACCEPTANCE: Send Message

---

Standard.AI.OpenAI.Tests.Acceptance/Clients/ChatCompletions/ChatCompletionClientTests.Send.cs
Standard.AI.OpenAI.Tests.Integration/APIs/ChatCompletions/ChatCompletionsApiTests.Send.cs
Standard.AI.OpenAI.Tests.Integration/APIs/ChatCompletions/ChatCompletionsApiTests.cs
Standard.AI.OpenAI.Tests.Integration/APIs/Completions/CompletionsApiTests.Prompts.cs
Standard.AI.OpenAI/Clients/ChatCompletions/ChatCompletionsClient.cs
Standard.AI.OpenAI/Clients/ChatCompletions/IChatCompletionsClient.cs

INTEGRATIONS: Send Chat Completion

---

Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/ChatCompletionDependencyValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/NullChatCompletionException.cs

CODE RUB: Add . (dot)

---

README.md

DOCUMENTATION: Add Completion Client Exceptions Documentation

---

README.md

DOCUMENTATIONS: Add Larger Icon

---

Standard.AI.OpenAI/Brokers/OpenAIs/IOpenAIBroker.ImageGenerations.cs
Standard.AI.OpenAI/Brokers/OpenAIs/OpenAIBroker.ImageGenerations.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalImageGenerations/ExternalImageGenerationRequest.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalImageGenerations/ExternalImageGenerationResponse.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalImageGenerations/ExternalImageGenerationResult.cs

BROKERS: POST Image Generation

---

Standard.AI.OpenAI/Brokers/DateTimes/DateTimeBroker.cs
Standard.AI.OpenAI/Brokers/DateTimes/IDateTimeBroker.cs

BROKERS: Convert to DateTimeOffSet

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ImageGenerations/ImageGenerationServiceTests.Exceptions.Generate.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ImageGenerations/ImageGenerationServiceTests.Logics.Generate.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ImageGenerations/ImageGenerationServiceTests.Validations.Generate.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ImageGenerations/ImageGenerationServiceTests.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/ExcessiveCallImageGenerationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/FailedImageGenerationServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/FailedServerImageGenerationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/ImageGenerationDependencyException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/ImageGenerationDependencyValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/ImageGenerationServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/ImageGenerationValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/InvalidConfigurationImageGenerationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/InvalidImageGenerationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/NotFoundImageGenerationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/NullImageGenerationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/UnauthorizedImageGenerationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/ImageGeneration.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/ImageGenerationRequest.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/ImageGenerationResponse.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/ImageGenerationResult.cs
Standard.AI.OpenAI/Services/Foundations/ImageGenerations/IImageGenerationService.cs
Standard.AI.OpenAI/Services/Foundations/ImageGenerations/ImageGenerationService.Exceptions.cs
Standard.AI.OpenAI/Services/Foundations/ImageGenerations/ImageGenerationService.Validations.cs
Standard.AI.OpenAI/Services/Foundations/ImageGenerations/ImageGenerationService.cs

FOUNDATIONS: Generate Image

---

README.md

DOCUMENTATIONS: Chat Completion Usage

---

README.md

DOCUMENTATIONS: Change Logo path to be a full Url

---

Standard.AI.OpenAI/Brokers/OpenAIs/OpenAIBroker.AudioTranscriptions.cs
Standard.AI.OpenAI/Brokers/OpenAIs/OpenAIBroker.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalAudioTranscriptions/ExternalAudioTranscriptionRequest.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalAudioTranscriptions/ExternalAudioTranscriptionResponse.cs

BROKERS: POST Audio File

---

Standard.AI.OpenAI/Models/Clients/ChatCompletions/Exceptions/ChatCompletionClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/ChatCompletions/Exceptions/ChatCompletionClientValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/InvalidConfigurationChatCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/UnauthorizedChatCompletionException.cs

CODE RUB: Change All Internal Exceptions To Public

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ImageGenerations/ImageGenerationServiceTests.Exceptions.Generate.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ImageGenerations/ImageGenerationServiceTests.Logics.Generate.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ImageGenerations/ImageGenerationServiceTests.Validations.Generate.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ImageGenerations/ImageGenerationServiceTests.cs
Standard.AI.OpenAI/Brokers/DateTimes/DateTimeBroker.cs
Standard.AI.OpenAI/Brokers/DateTimes/IDateTimeBroker.cs
Standard.AI.OpenAI/Clients/OpenAIs/OpenAIClient.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/ImageGenerationResponse.cs
Standard.AI.OpenAI/Services/Foundations/ImageGenerations/ImageGenerationService.cs

MINOR FIX: Change ImageGenerationResponse Created from Int to DateTimeOffset

---

Standard.AI.OpenAI.Tests.Integration/APIs/ImageGenerations/ImageGenerationApiTests.Generate.cs
Standard.AI.OpenAI.Tests.Integration/APIs/ImageGenerations/ImageGenerationApiTests.cs

INTEGRATIONS: Generate Image

---

Standard.AI.OpenAI.Tests.Acceptance/Clients/ImageGenerations/ImageGenerationClientTests.Generate.cs
Standard.AI.OpenAI.Tests.Acceptance/Clients/ImageGenerations/ImageGenerationClientTests.cs

ACCEPTANCES: Generate Image

---

Standard.AI.OpenAI.Tests.Acceptance/Clients/ChatCompletions/ChatCompletionClientTests.cs
Standard.AI.OpenAI.Tests.Acceptance/Clients/Completions/CompletionClientTests.cs
Standard.AI.OpenAI.Tests.Acceptance/Clients/ImageGenerations/ImageGenerationClientTests.cs
Standard.AI.OpenAI.Tests.Integration/APIs/ChatCompletions/ChatCompletionsApiTests.cs
Standard.AI.OpenAI.Tests.Integration/APIs/Completions/CompletionsApiTests.cs
Standard.AI.OpenAI.Tests.Integration/APIs/ImageGenerations/ImageGenerationApiTests.cs
Standard.AI.OpenAI/Brokers/OpenAIs/OpenAIBroker.cs
Standard.AI.OpenAI/Clients/OpenAIs/OpenAIClient.cs
Standard.AI.OpenAI/Models/Configurations/OpenAIConfigurations.cs

CODE RUB: Rename ApiConfigurations to OpenAIConfigurations

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ChatCompletions/ChatCompletionServiceTests.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.cs

MINOR FIX: Fix GetRandomBoolean

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIModels/AIModelServiceTests.Exceptions.Retrieve.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIModels/AIModelServiceTests.Logic.Retrieve.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIModels/AIModelServiceTests.cs
Standard.AI.OpenAI/Brokers/DateTimes/DateTimeBroker.cs
Standard.AI.OpenAI/Brokers/DateTimes/IDateTimeBroker.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/AIModel.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/AIModelPermission.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/AIModelDependencyException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/AIModelDependencyValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/AIModelServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/ExcessiveCallAIModelException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/FailedAIModelServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/FailedServerAIModelException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/InvalidConfigurationAIModelException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/UnauthorizedAIModelException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalAIModels/ExternalAIModel.cs
Standard.AI.OpenAI/Services/Foundations/AIModels/AIModelService.Exceptions.cs
Standard.AI.OpenAI/Services/Foundations/AIModels/AIModelService.cs
Standard.AI.OpenAI/Services/Foundations/AIModels/IAIModelService.cs

FOUNDATIONS: Retrieve AI Models

---

Standard.AI.OpenAI/Clients/AIModels/AIModelsClient.cs
Standard.AI.OpenAI/Clients/AIModels/IAIModelsClient.cs
Standard.AI.OpenAI/Clients/OpenAIs/IOpenAIClient.cs
Standard.AI.OpenAI/Clients/OpenAIs/OpenAIClient.cs
Standard.AI.OpenAI/Models/Clients/AIModels/Exceptions/AIModelClientDependencyValidationException.cs
Standard.AI.OpenAI/Models/Clients/AIModels/Exceptions/AIModelClientServiceException.cs
Standard.AI.OpenAI/Models/Clients/AIModels/Exceptions/AIModelClientValidationException.cs

CLIENTS: Retrieve All AI Models

---

Standard.AI.OpenAI.Tests.Integration/APIs/AIModels/AIModelsApiTests.RetrieveAll.cs
Standard.AI.OpenAI.Tests.Integration/APIs/AIModels/AIModelsApiTests.cs
Standard.AI.OpenAI/Clients/AIModels/AIModelsClient.cs

INTEGRATIONS: List All AI Models

---

Standard.AI.OpenAI.Tests.Acceptance/Clients/AIModels/AIModelsClientTests.RetrieveAll.cs
Standard.AI.OpenAI.Tests.Acceptance/Clients/AIModels/AIModelsClientTests.cs
Standard.AI.OpenAI.Tests.Acceptance/Clients/ChatCompletions/ChatCompletionClientTests.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIModels/AIModelServiceTests.Logic.Retrieve.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIModels/AIModelServiceTests.cs
Standard.AI.OpenAI/Services/Foundations/AIModels/AIModelService.cs
Standard.AI.OpenAI/Services/Foundations/AIModels/IAIModelService.cs

ACCEPTANCES: Retrieve All AI Models

---

Standard.AI.OpenAI/Standard.AI.OpenAI.csproj

RELEASES: Release v0.3 For Image Generation & Listing Models

---

Standard.AI.OpenAI/Services/Foundations/ImageGenerations/ImageGenerationService.Exceptions.cs

CODE RUB: Remove empty statement

---

Standard.AI.OpenAI.Tests.Acceptance/Clients/ChatCompletions/ChatCompletionClientTests.Send.cs
Standard.AI.OpenAI.Tests.Acceptance/Clients/Completions/CompletionClientTests.Prompts.cs
Standard.AI.OpenAI.Tests.Acceptance/Clients/ImageGenerations/ImageGenerationClientTests.Generate.cs

CODE RUB: Add `UsingPost()` in Acceptance Tests

---

README.md

DOCUMENTATIONS: Upgrade Example Code in Readme

---

Standard.AI.OpenAI/Services/Foundations/AIModels/AIModelService.cs

CODE RUB: Extract Mapping Logic From Method

---

Standard.AI.OpenAI.Tests.Acceptance/Clients/ImageGenerations/ImageGenerationClientTests.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ImageGenerations/ImageGenerationServiceTests.Exceptions.Generate.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ImageGenerations/ImageGenerationServiceTests.Logics.Generate.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ImageGenerations/ImageGenerationServiceTests.cs
Standard.AI.OpenAI/Services/Foundations/ImageGenerations/ImageGenerationService.cs

CODE RUB: Cleanup Image Generation Feature

---

Standard.AI.OpenAI.Tests.Acceptance/Clients/Completions/CompletionClientTests.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Exceptions.Prompt.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Logics.Prompt.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Validations.Prompt.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/CompletionResponse.cs
Standard.AI.OpenAI/Services/Foundations/Completions/CompletionService.cs

MEDIUM FIX: Change `CompletionResponse` `Created` from `int` to `DateTimeOffset`

---

Standard.AI.OpenAI/Clients/AIModels/AIModelsClient.cs

CODE RUB: Rename Variable Names

---

Standard.AI.OpenAI/Brokers/OpenAIs/IOpenAIBroker.AIModels.cs
Standard.AI.OpenAI/Brokers/OpenAIs/OpenAIBroker.AIModels.cs

BROKERS: Get AI Model By Id

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIModels/AIModelServiceTests.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ImageGenerations/ImageGenerationServiceTests.cs

MINOR FIX: Fix GetRandomDateNumber

---

README.md

DOCUMENTATIONS: Update YouTube Links To Playlist

---

Standard.AI.OpenAI/Brokers/Files/FileBroker.cs
Standard.AI.OpenAI/Brokers/Files/IFileBroker.cs
Standard.AI.OpenAI/Clients/OpenAIs/OpenAIClient.cs

BROKERS: Read File

---

README.md
Standard.AI.OpenAI/Clients/Completions/ICompletionsClient.cs
Standard.AI.OpenAI/Models/Clients/Completions/Exceptions/CompletionClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/Completions/Exceptions/CompletionClientServiceException.cs
Standard.AI.OpenAI/Models/Clients/Completions/Exceptions/CompletionClientValidationException.cs
Standard.AI.OpenAI/Standard.AI.OpenAI.csproj

DOCUMENTATIONS: Add XML Exception Explanations

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/LocalFiles/LocalFileServiceTests.Logic.Read.cs

CODE RUB: Dispose IDisposable Streams

---

Standard.AI.OpenAI/Clients/AIModels/AIModelsClient.cs
Standard.AI.OpenAI/Clients/AIModels/IAIModelsClient.cs
Standard.AI.OpenAI/Models/Clients/AIModels/Exceptions/AIModelClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/AIModels/Exceptions/AIModelClientServiceException.cs
Standard.AI.OpenAI/Models/Clients/AIModels/Exceptions/AIModelClientValidationException.cs

DOCUMENTATIONS: Document ALLAIModelsClient Methods & Exceptions

---

Standard.AI.OpenAI/Models/Services/Foundations/ExternalEdits/ExternalEditUsage.cs

CODE RUB: Fix Syntax `TotalPromptTokens`

---

Standard.AI.OpenAI.Tests.Acceptance/Clients/AIModels/AIModelsClientTests.cs

CODE RUB: Add IDisposable to AIModelsClientTests

---

Standard.AI.OpenAI.Tests.Acceptance/Clients/AIModels/AIModelsClientTests.RetrieveAll.cs
Standard.AI.OpenAI.Tests.Integration/APIs/AIModels/AIModelsApiTests.RetrieveAll.cs
Standard.AI.OpenAI/Clients/OpenAIs/IOpenAIClient.cs
Standard.AI.OpenAI/Clients/OpenAIs/OpenAIClient.cs

CODE RUB: Rename Property from `AllAIModels` to `AIModels`

---

Standard.AI.OpenAI/Brokers/OpenAIs/IOpenAIBroker.Files.cs
Standard.AI.OpenAI/Brokers/OpenAIs/OpenAIBroker.Files.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalFiles/ExternalFile.cs

BROKERS: Delete File By Id

---

Standard.AI.OpenAI/Clients/ImageGenerations/IImageGenerationsClient.cs
Standard.AI.OpenAI/Models/Clients/ImageGenerations/Exceptions/ImageGenerationClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/ImageGenerations/Exceptions/ImageGenerationClientServiceException.cs
Standard.AI.OpenAI/Models/Clients/ImageGenerations/Exceptions/ImageGenerationClientValidationException.cs

DOCUMENTATIONS: Document ImageGenerationClient Methods & Exceptions

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/LocalFiles/LocalFileServiceTests.Exceptions.Read.cs

CODE RUB: Rename Variable in Test

---

Standard.AI.OpenAI/Clients/ChatCompletions/IChatCompletionsClient.cs
Standard.AI.OpenAI/Models/Clients/ChatCompletions/Exceptions/ChatCompletionClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/ChatCompletions/Exceptions/ChatCompletionClientServiceException.cs
Standard.AI.OpenAI/Models/Clients/ChatCompletions/Exceptions/ChatCompletionClientValidationException.cs

DOCUMENTATIONS: Document `ChatCompletionClient` Methods & Exceptions

---

Standard.AI.OpenAI/Clients/AIModels/AIModelsClient.cs
Standard.AI.OpenAI/Clients/AIModels/IAIModelsClient.cs

CLIENTS: Retrieve AI Model By Name

---

Standard.AI.OpenAI.Tests.Acceptance/Clients/AIModels/AIModelsClientTests.RetrieveByName.cs
Standard.AI.OpenAI.Tests.Acceptance/Clients/AIModels/AIModelsClientTests.cs

ACCEPTANCES: Retrieve AI Model By Name

---

Standard.AI.OpenAI.Tests.Integration/APIs/AIModels/AIModelsApiTests.RetrieveByName.cs
Standard.AI.OpenAI.Tests.Integration/APIs/AIModels/AIModelsApiTests.cs

INTEGRATIONS: Retrieve AI Model By Name

---

Standard.AI.OpenAI/Standard.AI.OpenAI.csproj

RELEASES: Publish Retrieve AI Model By Name Package

---

README.md

CODE RUB: openAi url-> click  here hyperlinks

---

Standard.AI.OpenAI/Clients/AIFiles/AIFilesClient.cs
Standard.AI.OpenAI/Clients/AIFiles/IAIFilesClient.cs
Standard.AI.OpenAI/Clients/OpenAIs/IOpenAIClient.cs
Standard.AI.OpenAI/Clients/OpenAIs/OpenAIClient.cs
Standard.AI.OpenAI/Models/Clients/AIFiles/Exceptions/AIFileClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/AIFiles/Exceptions/AIFileClientServiceException.cs
Standard.AI.OpenAI/Models/Clients/AIFiles/Exceptions/AIFileClientValidationException.cs
Standard.AI.OpenAI/Models/Clients/AIModels/Exceptions/AIModelClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/AIModels/Exceptions/AIModelClientValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIFiles/AIFile.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIFiles/AIFileResponse.cs

CLIENTS: Upload File

---

Standard.AI.OpenAI.Tests.Integration/APIs/AIFiles/AIFilesTests.Upload.cs
Standard.AI.OpenAI.Tests.Integration/APIs/AIFiles/AIFilesTests.cs

INTEGRATIONS: Upload File

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Exceptions.Upload.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Logic.RemoveById.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Logic.Upload.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Validations.Uplaod.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.cs
Standard.AI.OpenAI/Brokers/OpenAIs/IOpenAIBroker.AIFiles.cs
Standard.AI.OpenAI/Brokers/OpenAIs/OpenAIBroker.AIFiles.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalAiFiles/ExternalAIFileRequest.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalAiFiles/ExternalAIFileResponse.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalAiFiles/ExternalAIFilesResult.cs
Standard.AI.OpenAI/Services/Foundations/AIFiles/AIFileService.cs

BROKERS: List Files

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Exceptions.RemoveById.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Exceptions.RetrieveAll.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Exceptions.Upload.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Logic.RemoveById.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Logic.RetrieveAll.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Logic.Upload.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Validations.RemoveById.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Validations.Uplaod.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIFiles/AIFileResponse.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIFiles/AIFileStatus.cs
Standard.AI.OpenAI/Models/Services/Foundations/ExternalAiFiles/ExternalAIFileResponse.cs
Standard.AI.OpenAI/Services/Foundations/AIFiles/AIFileService.Exceptions.cs
Standard.AI.OpenAI/Services/Foundations/AIFiles/AIFileService.cs
Standard.AI.OpenAI/Services/Foundations/AIFiles/IAIFileService.cs

FOUNDATIONS: List Files

---

Standard.AI.OpenAI/Clients/FineTunes/FineTuneClient.cs
Standard.AI.OpenAI/Clients/FineTunes/IFineTuneClient.cs
Standard.AI.OpenAI/Clients/OpenAIs/IOpenAIClient.cs
Standard.AI.OpenAI/Clients/OpenAIs/OpenAIClient.cs
Standard.AI.OpenAI/Models/Clients/FineTunes/Exceptions/FineTuneClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/FineTunes/Exceptions/FineTuneClientServiceException.cs
Standard.AI.OpenAI/Models/Clients/FineTunes/Exceptions/FineTuneClientValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/FineTunes/Exceptions/FailedFineTuneServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/FineTunes/Exceptions/FailedServerFineTuneException.cs
Standard.AI.OpenAI/Models/Services/Foundations/FineTunes/Exceptions/FineTuneDependencyException.cs
Standard.AI.OpenAI/Models/Services/Foundations/FineTunes/Exceptions/FineTuneServiceException.cs

CLIENTS: Fine Tune Client

---

Standard.AI.OpenAI.Tests.Unit/Services/Orchestrations/AIFiles/AIFileOrchestrationServiceTests.Exceptions.RetrieveAll.cs
Standard.AI.OpenAI.Tests.Unit/Services/Orchestrations/AIFiles/AIFileOrchestrationServiceTests.Logic.RetrieveAll.cs
Standard.AI.OpenAI.Tests.Unit/Services/Orchestrations/AIFiles/AIFileOrchestrationServiceTests.cs
Standard.AI.OpenAI/Services/Orchestrations/AIFiles/AIFileOrchestrationService.Exceptions.cs
Standard.AI.OpenAI/Services/Orchestrations/AIFiles/AIFileOrchestrationService.cs
Standard.AI.OpenAI/Services/Orchestrations/AIFiles/IAIFileOrchestrationService.cs

ORCHESTRATIONS: List Files

---

Standard.AI.OpenAI/Clients/AIFiles/AIFilesClient.cs
Standard.AI.OpenAI/Clients/AIFiles/IAIFilesClient.cs

CLIENTS: List Files

---

Standard.AI.OpenAI.Tests.Acceptance/Clients/FineTunes/FineTuneClientTests.Submit.cs
Standard.AI.OpenAI.Tests.Acceptance/Clients/FineTunes/FineTuneClientTests.cs

Acceptance: Submit Fine Tune

---

Standard.AI.OpenAI.Tests.Integration/APIs/AIFiles/AIFilesTests.RetrieveAll.cs

INTEGRATIONS: Get All Files

---

Standard.AI.OpenAI.Tests.Integration/APIs/FineTunes/FineTuneTests.Submit.cs
Standard.AI.OpenAI.Tests.Integration/APIs/FineTunes/FineTuneTests.cs

INTEGRATIONS: Submit Fine Tune Request

---

Standard.AI.OpenAI/Standard.AI.OpenAI.csproj

RELEASES: v0.6

---

.gitignore
Standard.AI.OpenAI.Tests.Unit/Services/Orchestrations/AIFiles/AIFileOrchestrationServiceTests.Exceptions.RemoveFileById.cs
Standard.AI.OpenAI.Tests.Unit/Services/Orchestrations/AIFiles/AIFileOrchestrationServiceTests.Logic.RemoveFileByIdAsync.cs
Standard.AI.OpenAI.Tests.Unit/Services/Orchestrations/AIFiles/AIFileOrchestrationServiceTests.Validation.RemoveFileByIdAsync.cs
Standard.AI.OpenAI.Tests.Unit/Services/Orchestrations/AIFiles/AIFileOrchestrationServiceTests.cs
Standard.AI.OpenAI/Services/Orchestrations/AIFiles/AIFileOrchestrationService.Validations.cs
Standard.AI.OpenAI/Services/Orchestrations/AIFiles/AIFileOrchestrationService.cs
Standard.AI.OpenAI/Services/Orchestrations/AIFiles/IAIFileOrchestrationService.cs

ORCHESTRATIONS: Remove file by Id

---

Standard.AI.OpenAI/Clients/AIFiles/AIFilesClient.cs
Standard.AI.OpenAI/Clients/AIFiles/IAIFilesClient.cs

CLIENTS : Remove File By Id

---

Standard.AI.OpenAI.Tests.Acceptance/Clients/AIFiles/AIFilesClientTests.RemoveById.cs
Standard.AI.OpenAI.Tests.Acceptance/Clients/AIFiles/AIFilesClientTests.cs

ACCEPTANCES : Remove File By Id

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Validations.Upload.cs

CODE RUB: Foundations AIFile Validations Tests Cleanup

---

Standard.AI.OpenAI.Tests.Acceptance/Clients/AIFiles/AIFilesClientTests.UploadFile.cs
Standard.AI.OpenAI.Tests.Acceptance/Clients/AIFiles/AIFilesClientTests.cs
Standard.AI.OpenAI.Tests.Acceptance/Standard.AI.OpenAI.Tests.Acceptance.csproj

ACCEPTANCES: Upload File

---

README.md

CODE RUB: Add Fine Tunes Client Example

---

README.md

DOCUMENTATIONS: Add Standard Versioning Badge

---

Standard.AI.OpenAI/Clients/FineTunes/IFineTuneClient.cs
Standard.AI.OpenAI/Models/Clients/FineTunes/Exceptions/FineTuneClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/FineTunes/Exceptions/FineTuneClientServiceException.cs
Standard.AI.OpenAI/Models/Clients/FineTunes/Exceptions/FineTuneClientValidationException.cs

DOCUMENTATIONS: Document Create Fine Tune Client Methods & Exceptions

---

Standard.AI.OpenAI/Clients/AIFiles/IAIFilesClient.cs
Standard.AI.OpenAI/Models/Clients/AIFiles/Exceptions/AIFileClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/AIFiles/Exceptions/AIFileClientServiceException.cs
Standard.AI.OpenAI/Models/Clients/AIFiles/Exceptions/AIFileClientValidationException.cs

DOCUMENTATIONS: Document Upload File Client Methods & Exceptions

---

Standard.AI.OpenAI/Clients/AIFiles/IAIFilesClient.cs
Standard.AI.OpenAI/Models/Clients/AIFiles/Exceptions/AIFileClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/AIFiles/Exceptions/AIFileClientServiceException.cs
Standard.AI.OpenAI/Models/Clients/AIFiles/Exceptions/AIFileClientValidationException.cs

DOCUMENTATIONS: Document Remove File By Id Methods & Exceptions

---

README.md

@hassanhabib Please review and merge.

DOCUMENTATIONS: Readme Badge Uniformity

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Exceptions.RemoveById.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Exceptions.RetrieveAll.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Exceptions.Upload.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Logic.RemoveById.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Logic.RetrieveAll.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Logic.Upload.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Validations.RemoveById.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIFiles/AIFileServiceTests.Validations.Upload.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIFiles/Exceptions/AIFileDependencyException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIFiles/Exceptions/AIFileDependencyValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIFiles/Exceptions/AIFileServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIFiles/Exceptions/AIFileValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIFiles/Exceptions/ExcessiveCallAIFileException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIFiles/Exceptions/FailedAIFileServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIFiles/Exceptions/FailedServerAIFileException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIFiles/Exceptions/InvalidAIFileException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIFiles/Exceptions/InvalidConfigurationAIFileException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIFiles/Exceptions/NotFoundAIFileException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIFiles/Exceptions/UnauthorizedAIFileException.cs

CODE RUB: AIFiles Exceptions Upgrade v2.10.0

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIModels/AIModelServiceTests.Exceptions.RetrieveAllModels.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIModels/AIModelServiceTests.Exceptions.RetrieveByName.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIModels/AIModelServiceTests.Logic.Retrieve.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIModels/AIModelServiceTests.Logic.RetrieveByName.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AIModels/AIModelServiceTests.Validations.RetrieveByName.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/AIModelDependencyException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/AIModelDependencyValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/AIModelServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/AIModelValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/ExcessiveCallAIModelException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/FailedAIModelServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/FailedServerAIModelException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/InvalidAIModelException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/InvalidConfigurationAIModelException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/NotFoundAIModelException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AIModels/Exceptions/UnauthorizedAIModelException.cs

CODE RUB: AIModels Exceptions Upgrade V2.10.0

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ChatCompletions/ChatCompletionServiceTests.Exceptions.Send.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ChatCompletions/ChatCompletionServiceTests.Logics.Send.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ChatCompletions/ChatCompletionServiceTests.Validations.Send.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/ChatCompletionDependencyException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/ChatCompletionDependencyValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/ChatCompletionServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/ChatCompletionValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/ExcessiveCallChatCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/FailedChatCompletionServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/FailedServerChatCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/InvalidChatCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/InvalidConfigurationChatCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/NotFoundChatCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/NullChatCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ChatCompletions/Exceptions/UnauthorizedChatCompletionException.cs

CODE RUB: ChatCompletions Exceptions Upgrade v2.10.0

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Exceptions.Prompt.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Logics.Prompt.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/Completions/CompletionServiceTests.Validations.Prompt.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/CompletionDependencyException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/CompletionDependencyValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/CompletionServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/CompletionValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/ExcessiveCallCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/FailedCompletionServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/FailedServerCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/InvalidCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/InvalidConfigurationCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/NotFoundCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/NullCompletionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/Completions/Exceptions/UnauthorizedCompletionException.cs

CODE RUB: Completions Exceptions Upgrade v2.10.0

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AudioTranscriptions/AudioTranscriptionServiceTests.Exceptions.Send.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AudioTranscriptions/AudioTranscriptionServiceTests.Logic.Send.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/AudioTranscriptions/AudioTranscriptionServiceTests.Validations.Send.cs
Standard.AI.OpenAI/Models/Services/Foundations/AudioTranscriptions/Exceptions/AudioTranscriptionDependencyException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AudioTranscriptions/Exceptions/AudioTranscriptionDependencyValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AudioTranscriptions/Exceptions/AudioTranscriptionServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AudioTranscriptions/Exceptions/AudioTranscriptionValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AudioTranscriptions/Exceptions/ExcessiveCallAudioTranscriptionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AudioTranscriptions/Exceptions/FailedAudioTranscriptionServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AudioTranscriptions/Exceptions/InvalidAudioTranscriptionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AudioTranscriptions/Exceptions/InvalidConfigurationAudioTranscriptionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AudioTranscriptions/Exceptions/NullAudioTranscriptionException.cs
Standard.AI.OpenAI/Models/Services/Foundations/AudioTranscriptions/Exceptions/UnauthorizedAudioTranscriptionException.cs

CODE RUB: AudioTranScriptions Exceptions Upgrade v2.10.0

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ImageGenerations/ImageGenerationServiceTests.Exceptions.Generate.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ImageGenerations/ImageGenerationServiceTests.Logics.Generate.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/ImageGenerations/ImageGenerationServiceTests.Validations.Generate.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/ExcessiveCallImageGenerationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/FailedImageGenerationServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/FailedServerImageGenerationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/ImageGenerationDependencyException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/ImageGenerationDependencyValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/ImageGenerationServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/ImageGenerationValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/InvalidConfigurationImageGenerationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/InvalidImageGenerationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/NotFoundImageGenerationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/NullImageGenerationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/ImageGenerations/Exceptions/UnauthorizedImageGenerationException.cs

CODE RUB: ImageGenerations Exceptions Upgrade v2.10.0

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/LocalFiles/LocalFileServiceTests.Exceptions.Read.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/LocalFiles/LocalFileServiceTests.Logic.Read.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/LocalFiles/LocalFileServiceTests.Validations.Read.cs
Standard.AI.OpenAI/Models/Services/Foundations/LocalFiles/Exceptions/FailedLocalFileDependencyException.cs
Standard.AI.OpenAI/Models/Services/Foundations/LocalFiles/Exceptions/FailedLocalFileServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/LocalFiles/Exceptions/InvalidLocalFileException.cs
Standard.AI.OpenAI/Models/Services/Foundations/LocalFiles/Exceptions/LocalFileDependencyException.cs
Standard.AI.OpenAI/Models/Services/Foundations/LocalFiles/Exceptions/LocalFileDependencyValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/LocalFiles/Exceptions/LocalFileServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/LocalFiles/Exceptions/LocalFileValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/LocalFiles/Exceptions/NotFoundLocalFileException.cs

CODE RUB: LocalFiles Exceptions Upgrade V2.10.0

---

Standard.AI.OpenAI/Clients/ChatCompletions/ChatCompletionsClient.cs
Standard.AI.OpenAI/Models/Clients/ChatCompletions/Exceptions/ChatCompletionClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/ChatCompletions/Exceptions/ChatCompletionClientServiceException.cs
Standard.AI.OpenAI/Models/Clients/ChatCompletions/Exceptions/ChatCompletionClientValidationException.cs

Updated all classes in the Models/Clients/ChatCompletions/Exceptions directory as well as the Clients/ChatCompletions/ChatCompletionsClient.cs file

CODE RUB: Clients ChatCompletions Exceptions Update v2.10.1 

---

Standard.AI.OpenAI/Clients/AIFiles/AIFilesClient.cs
Standard.AI.OpenAI/Models/Clients/AIFiles/Exceptions/AIFileClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/AIFiles/Exceptions/AIFileClientServiceException.cs
Standard.AI.OpenAI/Models/Clients/AIFiles/Exceptions/AIFileClientValidationException.cs

Updated all classes in the Models/Clients/AIFiles/Exceptions directory as well as the Clients/AIFiles/AIFilesClient.cs file

CODE RUB: Clients AIFiles Exceptions Update v2.10.1 

---

Standard.AI.OpenAI/Clients/AIModels/AIModelsClient.cs
Standard.AI.OpenAI/Models/Clients/AIModels/Exceptions/AIModelClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/AIModels/Exceptions/AIModelClientServiceException.cs
Standard.AI.OpenAI/Models/Clients/AIModels/Exceptions/AIModelClientValidationException.cs

Updated all classes in the Models/Clients/AIModels/Exceptions directory as well as the Clients/AIModels/AIModelsClient.cs file.

CODE RUB: Clients AIModels Exceptions Update v2.10.1 

---

Standard.AI.OpenAI/Clients/FineTunes/FineTuneClient.cs
Standard.AI.OpenAI/Models/Clients/FineTunes/Exceptions/FineTuneClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/FineTunes/Exceptions/FineTuneClientServiceException.cs
Standard.AI.OpenAI/Models/Clients/FineTunes/Exceptions/FineTuneClientValidationException.cs

Updated all classes in the Models/Clients/FineTunes/Exceptions directory as well as the Clients/FineTunes/FineTunesClient.cs file.

CODE RUB: Clients FineTunes Exceptions Update v2.10.1 

---

Standard.AI.OpenAI/Clients/ImageGenerations/ImageGenerationsClient.cs
Standard.AI.OpenAI/Models/Clients/ImageGenerations/Exceptions/ImageGenerationClientDependencyException.cs
Standard.AI.OpenAI/Models/Clients/ImageGenerations/Exceptions/ImageGenerationClientServiceException.cs
Standard.AI.OpenAI/Models/Clients/ImageGenerations/Exceptions/ImageGenerationClientValidationException.cs

Updated all classes in the Models/Clients/ImageGenerations/Exceptions directory as well as the Clients/ImageGenerations/ImageGenerationsClient.cs file.

CODE RUB: Clients ImageGenerations Exceptions Update v2.10.1 

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/LocalFiles/LocalFileServiceTests.Validations.Read.cs
Standard.AI.OpenAI.Tests.Unit/Services/Orchestrations/AIFiles/AIFileOrchestrationServiceTests.cs
Standard.AI.OpenAI/Models/Services/Foundations/LocalFiles/Exceptions/FailedLocalFileDependencyException.cs
Standard.AI.OpenAI/Models/Services/Foundations/LocalFiles/Exceptions/FailedLocalFileServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/LocalFiles/Exceptions/InvalidLocalFileException.cs
Standard.AI.OpenAI/Models/Services/Foundations/LocalFiles/Exceptions/LocalFileDependencyException.cs
Standard.AI.OpenAI/Models/Services/Foundations/LocalFiles/Exceptions/LocalFileDependencyValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/LocalFiles/Exceptions/LocalFileServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/LocalFiles/Exceptions/LocalFileValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/LocalFiles/Exceptions/NotFoundLocalFileException.cs
Standard.AI.OpenAI/Services/Foundations/LocalFiles/LocalFileService.Exceptions.cs
Standard.AI.OpenAI/Services/Foundations/LocalFiles/LocalFileService.Validations.cs

Updated all classes in the Models/Services/Foundations/LocalFiles/Exceptions directory as well as the files in the Services/Foundations/LocalFiles directory.

CODE RUB: Foundations LocalFiles Exceptions Update v2.10.1

---

Standard.AI.OpenAI.Tests.Unit/Services/Foundations/FineTunes/FineTuneServiceTests.Validations.Submit.cs
Standard.AI.OpenAI.Tests.Unit/Services/Foundations/FineTunes/FineTuneServiceTests.cs
Standard.AI.OpenAI/Models/Services/Foundations/FineTunes/Exceptions/ExcessiveCallFineTuneException.cs
Standard.AI.OpenAI/Models/Services/Foundations/FineTunes/Exceptions/FailedFineTuneServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/FineTunes/Exceptions/FailedServerFineTuneException.cs
Standard.AI.OpenAI/Models/Services/Foundations/FineTunes/Exceptions/FineTuneDependencyException.cs
Standard.AI.OpenAI/Models/Services/Foundations/FineTunes/Exceptions/FineTuneDependencyValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/FineTunes/Exceptions/FineTuneServiceException.cs
Standard.AI.OpenAI/Models/Services/Foundations/FineTunes/Exceptions/FineTuneValidationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/FineTunes/Exceptions/InvalidFineTuneConfigurationException.cs
Standard.AI.OpenAI/Models/Services/Foundations/FineTunes/Exceptions/InvalidFineTuneException.cs
Standard.AI.OpenAI/Models/Services/Foundations/FineTunes/Exceptions/NullFineTuneException.cs
Standard.AI.OpenAI/Models/Services/Foundations/FineTunes/Exceptions/UnauthorizedFineTuneException.cs
Standard.AI.OpenAI/Services/Foundations/FineTunes/FineTuneService.Exceptions.cs
Standard.AI.OpenAI/Services/Foundations/FineTunes/FineTuneService.Validations.cs

Updated all classes in the Models/Services/Foundations/FineTunes/Exceptions directory as well as the files in the Services/Foundations/FineTunes directory.

CODE RUB: Foundations FineTunes Exceptions Update v2.10.1 

---

README.md

In Response to #560. Updated Readme file. Set the standard version badge to current 2.10.2.
Closes #560.

DOCUMENTATION: Update Readme V2.10.2
